---
name: test

"on":
  push: {}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PYTHON_SPOOF_VENV: ${GITHUB_WORKSPACE}/.venv/bin/python

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Fetch master (for incremental diff, lint filter mask)
        run: git fetch origin master

      - name: Reload Cache / pip
        uses: actions/setup-python@v4
        with:
          python-version: 3
          update-environment: false
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install requirements
        run: PYTHON=${{ env.PYTHON_SPOOF_VENV }} make deps

      - name: Lint
        run: PYTHON=${{ env.PYTHON_SPOOF_VENV }} make lint

      - name: Test
        continue-on-error: true
        run: PYTHON=${{ env.PYTHON_SPOOF_VENV }} make test

      - name: Basic CLI Integration Tests
        run: |
          ./sp fetch
          ./sp -c stand -t DET
          ./sp -c stand -t "Detroit Red Wings"
