---
name: update-csv

"on":
  workflow_dispatch:
  schedule:
    # At minute 0 past every hour.
    - cron: "0 */1 * * *"

permissions:
  contents: write

jobs:
  update-csv:
    runs-on: ubuntu-latest

    env:
      PYTHON_SPOOF_VENV: ${GITHUB_WORKSPACE}/.venv/bin/python

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Reload Cache / pip
        uses: actions/setup-python@v4
        with:
          python-version: 3
          update-environment: false
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install requirements
        run: PYTHON=${{ env.PYTHON_SPOOF_VENV }} make deps

      - name: Fetch
        run: ./sp --debug fetch

      - name: Update standings
        run: |
          sp stand -c >output/Standings.txt
          # Standings (sorted by specific column)
          sort_cols=(
            rating
            avg_opp
            rating_max
            rating_avg
            goals_for
            goals_against
            last_10
            streak
          )
          for col in "${sort_cols[@]}"; do \
            sp stand -c -s $col >output/Standings-$col.txt; \
          done

      - name: Update team statistics
        run: |
          for team in $(sp teams --abbrev-only); do \
            sp stand -c -t $team | tee output/Team-$team.txt \
          done

      - name: Commit changes (to CSV)
        env:
          INPUT_AUTHOR_USER_NAME: "github-actions[bot]"
          INPUT_AUTHOR_USER_EMAIL: "github-actions[bot]@users.noreply.github.com"
          INPUT_COMMIT_USER_NAME: "github-actions[bot]"
          INPUT_COMMIT_USER_EMAIL: "github-actions[bot]@users.noreply.github.com"
          INPUT_COMMIT_MESSAGE: "Add games to CSV (automated workflow)"
        uses: stefanzweifel/git-auto-commit-action@v4
